In [1]:
import pandas as pd
import numpy as np

In [2]:
#读取表达矩阵
long_rna_seq = pd.read_csv('./long RNA-seq/count.matrix.long.txt', index_col=0, sep='\t')
small_rna_seq = pd.read_csv('./small RNA-seq/count.matrix.short.txt', index_col=0, sep='\t')
long_rna_seq.head()
small_rna_seq.head()

,Sample_1S1,Sample_1S10,Sample_1S11,Sample_1S12,Sample_1S13,Sample_1S14,Sample_1S15,Sample_1S16,Sample_1S17,Sample_1S18,...,Sample_PC6,Sample_PC7,Sample_PC8,Sample_PC9,Sample_Pan01,Sample_Pan02,Sample_Pan03,Sample_Pan04,Sample_Pan05,Sample_Pan06
gene_id,,,,,,,,,,,,,,,,,,,,,
hsa-let-7a-1,1017,2264,2154,632,2528,2366,1490,1870,845,647,...,914,592,2001,2166,649,635,534,323,605,549
hsa-let-7a-2,840,1833,1943,560,2258,2066,1291,1637,771,565,...,803,537,1675,1961,562,556,448,284,504,475
hsa-let-7a-3,936,2171,2152,682,2394,2341,1524,1847,851,689,...,939,580,1906,2267,676,591,518,348,606,570
hsa-let-7b,47637,61737,68089,55949,44364,32884,24138,44253,41995,25356,...,59906,36018,53997,64527,14768,14917,21369,14354,16602,16307
hsa-let-7c,2818,8759,5728,2376,6907,3850,2949,3737,3673,1805,...,3447,1812,4768,5619,1442,1280,1598,847,1293,1485

In [3]:
# 读取批次信息
long_rna_meta = pd.read_csv('./long RNA-seq/metadata.long.txt', index_col=0, sep='\t')
small_rna_meta = pd.read_csv('./small RNA-seq/metadata.short.txt', index_col=0, sep='\t')
# 缺失值处理
long_rna_seq = long_rna_seq.fillna(0)
small_rna_seq = small_rna_seq.fillna(0)
long_rna_meta.head()
small_rna_meta.head()

,RNA Isolation batch,library prepration day,gel cut size selection,label,sex,id,stage,dataset
sample id,,,,,,,,
Sample_1S1,2,22,7,CRC,F,GSM1825212,I,train
Sample_1S10,3,24,1,CRC,F,GSM1825215,I,train
Sample_1S11,3,24,2,CRC,F,GSM1825239,I,test
Sample_1S12,3,25,7,CRC,M,GSM1825071,I,train
Sample_1S13,4,26,2,CRC,F,GSM1825216,I,train

In [4]:
# 将表达矩阵归一化，计算RPM
long_rna_sample_sum = long_rna_seq.sum(axis=0)
small_rna_sample_sum = small_rna_seq.sum(axis=0)
long_rna_seq_cpm = long_rna_seq.div(long_rna_sample_sum, axis=1) * 1e6
small_rna_seq_cpm = small_rna_seq.div(small_rna_sample_sum, axis=1) * 1e6
long_rna_seq_cpm.head()
small_rna_seq_cpm.head()

,Sample_1S1,Sample_1S10,Sample_1S11,Sample_1S12,Sample_1S13,Sample_1S14,Sample_1S15,Sample_1S16,Sample_1S17,Sample_1S18,...,Sample_PC6,Sample_PC7,Sample_PC8,Sample_PC9,Sample_Pan01,Sample_Pan02,Sample_Pan03,Sample_Pan04,Sample_Pan05,Sample_Pan06
gene_id,,,,,,,,,,,,,,,,,,,,,
hsa-let-7a-1,221.023628,522.145640,431.622846,112.449553,438.481010,427.683370,337.849788,346.044261,135.610934,161.086405,...,168.688187,202.277121,461.200074,468.075662,259.885458,287.669142,236.332753,168.809537,274.024225,201.577667
hsa-let-7a-2,182.556389,422.744240,389.342242,99.638845,391.649573,373.454709,292.727568,302.927516,123.734947,140.670508,...,148.201985,183.484483,386.062031,423.774872,225.047192,251.880382,198.271673,148.426962,228.278032,174.406906
hsa-let-7a-3,203.419977,500.697078,431.222082,121.345879,415.238741,423.164315,345.559112,341.788101,136.573852,171.543327,...,173.302197,198.176909,439.304019,489.901905,270.697334,267.736162,229.251622,181.875291,274.477157,209.288288
hsa-let-7b,10352.903233,14238.385777,13643.810560,9954.810225,7694.925450,5944.184247,5473.166564,8189.035652,6739.622674,6312.993623,...,11056.274121,12306.786056,12445.487465,13944.375928,5913.695603,6757.733203,9457.293255,7501.833125,7519.587070,5987.480889
hsa-let-7c,612.433220,2020.085541,1147.788143,422.753384,1198.017539,695.934477,668.670486,691.533370,589.466224,449.398702,...,636.179630,619.131999,1098.951502,1214.273844,577.434254,579.868506,707.227976,442.667734,585.641855,545.251065

In [5]:
# 过滤表达量低的基因
min_cpm = 1
min_samples = 2
mask_long_rna = (long_rna_seq_cpm >= min_cpm).sum(axis=1) >= min_samples
mask_small_rna = (small_rna_seq_cpm >= min_cpm).sum(axis=1) >= min_samples
long_rna_seq_filtered = long_rna_seq_cpm.loc[mask_long_rna]
small_rna_seq_filtered = small_rna_seq_cpm.loc[mask_small_rna]
long_rna_seq_filtered.head()
small_rna_seq_filtered.head()

,Sample_1S1,Sample_1S10,Sample_1S11,Sample_1S12,Sample_1S13,Sample_1S14,Sample_1S15,Sample_1S16,Sample_1S17,Sample_1S18,...,Sample_PC6,Sample_PC7,Sample_PC8,Sample_PC9,Sample_Pan01,Sample_Pan02,Sample_Pan03,Sample_Pan04,Sample_Pan05,Sample_Pan06
gene_id,,,,,,,,,,,,,,,,,,,,,
hsa-let-7a-1,221.023628,522.145640,431.622846,112.449553,438.481010,427.683370,337.849788,346.044261,135.610934,161.086405,...,168.688187,202.277121,461.200074,468.075662,259.885458,287.669142,236.332753,168.809537,274.024225,201.577667
hsa-let-7a-2,182.556389,422.744240,389.342242,99.638845,391.649573,373.454709,292.727568,302.927516,123.734947,140.670508,...,148.201985,183.484483,386.062031,423.774872,225.047192,251.880382,198.271673,148.426962,228.278032,174.406906
hsa-let-7a-3,203.419977,500.697078,431.222082,121.345879,415.238741,423.164315,345.559112,341.788101,136.573852,171.543327,...,173.302197,198.176909,439.304019,489.901905,270.697334,267.736162,229.251622,181.875291,274.477157,209.288288
hsa-let-7b,10352.903233,14238.385777,13643.810560,9954.810225,7694.925450,5944.184247,5473.166564,8189.035652,6739.622674,6312.993623,...,11056.274121,12306.786056,12445.487465,13944.375928,5913.695603,6757.733203,9457.293255,7501.833125,7519.587070,5987.480889
hsa-let-7c,612.433220,2020.085541,1147.788143,422.753384,1198.017539,695.934477,668.670486,691.533370,589.466224,449.398702,...,636.179630,619.131999,1098.951502,1214.273844,577.434254,579.868506,707.227976,442.667734,585.641855,545.251065

In [11]:
# 消除批次效应
batch_set = small_rna_meta['RNA Isolation batch']
batch_set

sample id
Sample_1S1     2
Sample_1S10    3
Sample_1S11    3
Sample_1S12    3
Sample_1S13    4
              ..
Sample_PC5     2
Sample_PC6     2
Sample_PC7     6
Sample_PC8     6
Sample_PC9     6
Name: RNA Isolation batch, Length: 192, dtype: int64

In [13]:
idx = np.argsort(batch_set)
idx

sample id
Sample_1S1      23
Sample_1S10     24
Sample_1S11     22
Sample_1S12     47
Sample_1S13     48
              ...
Sample_PC5     153
Sample_PC6     150
Sample_PC7     151
Sample_PC8     154
Sample_PC9     155
Name: RNA Isolation batch, Length: 192, dtype: int64